# Generated by Django 4.0.6 on 2022-07-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='author',
            field=models.CharField(default='anonymus', max_length=150),
        ),
    ]
